export const messageBenignidade = [
  {
    id: "be1",
    author: "Danyllo Aniceto",
    instagram: "danylloaniceto",
    title: "Gratidão ao Perdão Imerecido",
    verse: [
      "'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.'",
      "(Efésios 4: 32)",
    ],
    text: [
      "Nós, filhos de Deus, por meio de Cristo Jesus, compreendemos que não somos aceitos de forma merecida. Não merecemos o perdão de Deus, pois nossas atitudes revelam que somos incapazes de seguir a perfeição necessária para estar diante da presença do Todo-Poderoso. Quando pecamos, estamos nos afastando de Deus, rompendo a ligação e satisfazendo os nossos próprios desejos que nos levam à destruição e à morte.",
      "‘Pois todos pecaram e estão destituídos da glória de Deus, sendo justificados gratuitamente por sua graça, por meio da redenção que há em Cristo Jesus. Deus o ofereceu como sacrifício para expiação pelo seu sangue, para ser recebido pela fé, de forma a demonstrar sua justiça. Isto porque, na sua tolerância, deixou impunes os pecados anteriormente cometidos. Todavia, no presente, Deus demonstrou a sua justiça, a fim de ser justo e justificador daquele que tem fé em Jesus.’ – Romanos 3:23-26",
      "Jesus nos trouxe a esperança. Pelo imensurável amor de Deus, Cristo fez justiça por nós. Somos aceitos através do sangue do Cordeiro mediante a fé. Todos os nossos dias devemos nos recordar e agradecer por tal feito. Deus nos ama de fato e nos concedeu um caminho de vida eterna. Que possamos sempre nos alegrar com isso: Jesus é o único caminho, a verdade e a vida.",
      "Portanto, quando estamos andando pelo caminho da graça, seguimos os mandamentos que Cristo nos deixou, e um dos principais está relacionado ao perdão entre nós. Assim como Deus nos demonstrou misericórdia, devemos aplicá-la às pessoas deste mundo.",
      "‘Não julguem, e vocês não serão julgados. Não condenem, e não serão condenados. Perdoem, e serão perdoados.’ – Lucas 6:37",
      "O perdão nos leva a tratar o nosso próximo de forma benigna. Mesmo que ele possa errar e nos ferir de certa forma, e até mesmo se não demonstrar arrependimento, devemos fazer a nossa parte. Não devemos guardar nenhuma mágoa e fazer com que a dívida que ele tinha conosco não seja mais motivo de julgamento, ira ou vingança, pois isso não pertence a nós. No momento em que vivemos, devemos apenas seguir aquilo que Cristo estabeleceu: amar a Deus sobre todas as coisas e ao próximo como a si mesmo. A justiça terá o seu tempo, e não seremos nós os juízes, mas sim Deus. Por enquanto, vivemos debaixo da graça, e nosso comportamento deve ser aquilo que Jesus nos mandou fazer.",
      "A seguir, veremos a parábola do servo mau, que reflete toda esta mensagem:",
      "‘Então, Pedro aproximou-se de Jesus e perguntou: ― Senhor, quantas vezes deverei perdoar o meu irmão quando ele pecar contra mim? Até sete vezes? Jesus respondeu: ― Eu digo a você que não até sete, mas até setenta vezes sete. ― Por isso, o reino dos céus é como um rei que desejava acertar contas com os seus servos. Quando começou o acerto, foi trazido à sua presença um que lhe devia dez mil talentos. Como não tinha condições de pagar, o senhor ordenou que ele, a sua mulher, os seus filhos e tudo o que ele possuía fossem vendidos para pagar a dívida. ― O servo prostrou-se diante dele e implorou: ‘Tem paciência comigo, e tudo te pagarei’. O senhor daquele servo teve compaixão dele, cancelou a dívida e o deixou ir. ― Mas, quando aquele servo saiu, encontrou um dos seus conservos que lhe devia cem denários. Ele o agarrou e começou a sufocá-lo, dizendo: ‘Pague o que me deve!’. ― Então, o seu conservo caiu de joelhos e implorou-lhe: ‘Tenha paciência comigo, e pagarei a você’. ― Ele, porém, não quis. Antes, saiu e mandou lançá-lo na prisão, até que pagasse a dívida. Quando os servos que eram companheiros dele viram o que havia acontecido, ficaram muito tristes e foram contar tudo ao seu senhor. ― Então, o senhor chamou o servo e disse: ‘Servo mau, cancelei toda a sua dívida porque você me implorou. Não deveria você ter tido misericórdia do seu conservo, como eu tive de você?’. Irado, o seu senhor entregou-o aos torturadores, até que pagasse tudo o que devia. ― Assim também fará o meu Pai celestial a vocês se cada um não perdoar de coração o seu irmão.’ – Mateus 18: 21-35",
      "Assim, aprendemos que, se não aplicarmos o perdão, seremos castigados, já que, uma vez que fomos perdoados pelo próprio Deus, quem somos nós para não perdoar o nosso próximo? Ao contrário do servo mau, que não aprendeu a lição com seu patrão, devemos agir de forma grata.",
      "Somos gratos ao Senhor, pois sem Ele não haveria salvação. Não há peso nenhum em obedecer aos seus mandamentos, pois o amor nos transforma e nos faz compreender que tudo o que Ele diz é bom, perfeito e agradável. Então, que nunca esqueçamos de suas ordenanças e, durante toda a nossa vida, perdoemos a todos que tivermos que perdoar, pois Ele nos perdoou.",
    ],
  },
];
